import subprocess
import os

experiments = [
    ['python3', 'aglo_learned_nodes.py', '-int', '[2,21]', '-st', '/Users/antoniomendez/Library/CloudStorage/GoogleDrive-angel.mendez@cimat.mx/Mi unidad/Tesis/Datos/Adj_eco/matrices_estaciones/est_2024.npy', '-cell', 'station_cells/station_cells_ecobici_2024_4.pkl', '-nodes', 'station_cells/nodes_eco_4.npy', '-index', '259', '-sys', 'ecobici', '-part', '4', '-input', '/Users/antoniomendez/Library/CloudStorage/GoogleDrive-angel.mendez@cimat.mx/Mi unidad/angel_inference_dictionary_learning/eco/results_2024_22n_12a_reg', '-out', f'nodes_clustering_results/day_1609_eco_22n_12a_reg'],
    ['python3', 'aglo_learned_nodes.py', '-int', '[2,21]', '-st', '/Users/antoniomendez/Library/CloudStorage/GoogleDrive-angel.mendez@cimat.mx/Mi unidad/Tesis/Datos/Adj_eco/matrices_estaciones/est_2024.npy', '-cell', 'station_cells/station_cells_ecobici_2024_4.pkl', '-nodes', 'station_cells/nodes_eco_4.npy', '-index', '259', '-sys', 'ecobici', '-part', '4', '-input', '/Users/antoniomendez/Library/CloudStorage/GoogleDrive-angel.mendez@cimat.mx/Mi unidad/angel_inference_dictionary_learning/eco/results_2024_22n_12a_noreg', '-out', f'nodes_clustering_results/day_1609_eco_22n_12a_noreg'],
    ['python3', 'aglo_learned_nodes.py', '-int', '[2,21]', '-st', '/Users/antoniomendez/Library/CloudStorage/GoogleDrive-angel.mendez@cimat.mx/Mi unidad/Tesis/Datos/Adj_mibici/matrices_estaciones/est_2024.npy', '-cell', 'station_cells/station_cells_mibici_2024_6.pkl', '-nodes', 'station_cells/nodes_mibici_6.npy', '-index', '259', '-sys', 'mibici', '-part', '6', '-input', '/Users/antoniomendez/Library/CloudStorage/GoogleDrive-angel.mendez@cimat.mx/Mi unidad/angel_inference_dictionary_learning/mibici/results_2024_22n_12a_reg', '-out', f'nodes_clustering_results/day_1609_mibici_22n_12a_reg'],
    ['python3', 'aglo_learned_nodes.py', '-int', '[2,21]', '-st', '/Users/antoniomendez/Library/CloudStorage/GoogleDrive-angel.mendez@cimat.mx/Mi unidad/Tesis/Datos/Adj_mibici/matrices_estaciones/est_2024.npy', '-cell', 'station_cells/station_cells_mibici_2024_6.pkl', '-nodes', 'station_cells/nodes_mibici_6.npy', '-index', '259', '-sys', 'mibici', '-part', '6', '-input', '/Users/antoniomendez/Library/CloudStorage/GoogleDrive-angel.mendez@cimat.mx/Mi unidad/angel_inference_dictionary_learning/mibici/results_2024_22n_12a_noreg', '-out', f'nodes_clustering_results/day_1609_mibici_22n_12a_noreg'],
    ['python3', 'aglo_learned_nodes.py', '-int', '[2,45]', '-st', '/Users/antoniomendez/Library/CloudStorage/GoogleDrive-angel.mendez@cimat.mx/Mi unidad/Tesis/Datos/Adj_eco/matrices_estaciones/est_2024.npy', '-cell', 'station_cells/station_cells_ecobici_2024_6.pkl', '-nodes', 'station_cells/nodes_eco_6.npy', '-index', '259', '-sys', 'ecobici', '-part', '6', '-input', '/Users/antoniomendez/Library/CloudStorage/GoogleDrive-angel.mendez@cimat.mx/Mi unidad/angel_inference_dictionary_learning/eco/results_2024_46n_23a_reg', '-out', f'nodes_clustering_results/day_1609_eco_46n_23a_reg'],
    ['python3', 'aglo_learned_nodes.py', '-int', '[2,45]', '-st', '/Users/antoniomendez/Library/CloudStorage/GoogleDrive-angel.mendez@cimat.mx/Mi unidad/Tesis/Datos/Adj_eco/matrices_estaciones/est_2024.npy', '-cell', 'station_cells/station_cells_ecobici_2024_6.pkl', '-nodes', 'station_cells/nodes_eco_6.npy', '-index', '259', '-sys', 'ecobici', '-part', '6', '-input', '/Users/antoniomendez/Library/CloudStorage/GoogleDrive-angel.mendez@cimat.mx/Mi unidad/angel_inference_dictionary_learning/eco/results_2024_46n_23a_noreg', '-out', f'nodes_clustering_results/day_1609_eco_46n_23a_noreg'],
    ['python3', 'aglo_learned_nodes.py', '-int', '[2,44]', '-st', '/Users/antoniomendez/Library/CloudStorage/GoogleDrive-angel.mendez@cimat.mx/Mi unidad/Tesis/Datos/Adj_mibici/matrices_estaciones/est_2024.npy', '-cell', 'station_cells/station_cells_mibici_2024_10.pkl', '-nodes', 'station_cells/nodes_mibici_10.npy', '-index', '259', '-sys', 'mibici', '-part', '10', '-input', '/Users/antoniomendez/Library/CloudStorage/GoogleDrive-angel.mendez@cimat.mx/Mi unidad/angel_inference_dictionary_learning/mibici/results_2024_45n_22a_reg', '-out', f'nodes_clustering_results/day_1609_mibici_45n_22a_reg'],
    ['python3', 'aglo_learned_nodes.py', '-int', '[2,44]', '-st', '/Users/antoniomendez/Library/CloudStorage/GoogleDrive-angel.mendez@cimat.mx/Mi unidad/Tesis/Datos/Adj_mibici/matrices_estaciones/est_2024.npy', '-cell', 'station_cells/station_cells_mibici_2024_10.pkl', '-nodes', 'station_cells/nodes_mibici_10.npy', '-index', '259', '-sys', 'mibici', '-part', '10', '-input', '/Users/antoniomendez/Library/CloudStorage/GoogleDrive-angel.mendez@cimat.mx/Mi unidad/angel_inference_dictionary_learning/mibici/results_2024_45n_22a_noreg', '-out', f'nodes_clustering_results/day_1609_mibici_45n_22a_noreg'],
    ['python3', 'aglo_learned_nodes.py', '-int', '[2,45]', '-st', '/Users/antoniomendez/Library/CloudStorage/GoogleDrive-angel.mendez@cimat.mx/Mi unidad/Tesis/Datos/Adj_eco/matrices_estaciones/est_2024.npy', '-cell', 'station_cells/station_cells_ecobici_2024_6.pkl', '-nodes', 'station_cells/nodes_eco_6.npy', '-index', '275', '-sys', 'ecobici', '-part', '6', '-input', '/Users/antoniomendez/Library/CloudStorage/GoogleDrive-angel.mendez@cimat.mx/Mi unidad/angel_inference_dictionary_learning/eco/results_2024_46n_23a_reg', '-out', f'nodes_clustering_results/day_0210_eco_46n_23a_reg'],
    ['python3', 'aglo_learned_nodes.py', '-int', '[2,45]', '-st', '/Users/antoniomendez/Library/CloudStorage/GoogleDrive-angel.mendez@cimat.mx/Mi unidad/Tesis/Datos/Adj_eco/matrices_estaciones/est_2024.npy', '-cell', 'station_cells/station_cells_ecobici_2024_6.pkl', '-nodes', 'station_cells/nodes_eco_6.npy', '-index', '275', '-sys', 'ecobici', '-part', '6', '-input', '/Users/antoniomendez/Library/CloudStorage/GoogleDrive-angel.mendez@cimat.mx/Mi unidad/angel_inference_dictionary_learning/eco/results_2024_46n_23a_noreg', '-out', f'nodes_clustering_results/day_0210_eco_46n_23a_noreg'],
    ['python3', 'aglo_learned_nodes.py', '-int', '[2,44]', '-st', '/Users/antoniomendez/Library/CloudStorage/GoogleDrive-angel.mendez@cimat.mx/Mi unidad/Tesis/Datos/Adj_mibici/matrices_estaciones/est_2024.npy', '-cell', 'station_cells/station_cells_mibici_2024_10.pkl', '-nodes', 'station_cells/nodes_mibici_10.npy', '-index', '275', '-sys', 'mibici', '-part', '10', '-input', '/Users/antoniomendez/Library/CloudStorage/GoogleDrive-angel.mendez@cimat.mx/Mi unidad/angel_inference_dictionary_learning/mibici/results_2024_45n_22a_reg', '-out', f'nodes_clustering_results/day_0210_mibici_45n_22a_reg'],
    ['python3', 'aglo_learned_nodes.py', '-int', '[2,44]', '-st', '/Users/antoniomendez/Library/CloudStorage/GoogleDrive-angel.mendez@cimat.mx/Mi unidad/Tesis/Datos/Adj_mibici/matrices_estaciones/est_2024.npy', '-cell', 'station_cells/station_cells_mibici_2024_10.pkl', '-nodes', 'station_cells/nodes_mibici_10.npy', '-index', '275', '-sys', 'mibici', '-part', '10', '-input', '/Users/antoniomendez/Library/CloudStorage/GoogleDrive-angel.mendez@cimat.mx/Mi unidad/angel_inference_dictionary_learning/mibici/results_2024_45n_22a_noreg', '-out', f'nodes_clustering_results/day_0210_mibici_45n_22a_noreg'],
    ['python3', 'aglo_learned_nodes.py', '-int', '[2,21]', '-st', '/Users/antoniomendez/Library/CloudStorage/GoogleDrive-angel.mendez@cimat.mx/Mi unidad/Tesis/Datos/Adj_eco/matrices_estaciones/est_2024.npy', '-cell', 'station_cells/station_cells_ecobici_2024_6.pkl', '-nodes', 'station_cells/nodes_eco_6.npy', '-index', '275', '-sys', 'ecobici', '-part', '6', '-input', '/Users/antoniomendez/Library/CloudStorage/GoogleDrive-angel.mendez@cimat.mx/Mi unidad/angel_inference_dictionary_learning/eco/results_2024_22n_12a_reg', '-out', f'nodes_clustering_results/day_0210_eco_22n_12a_reg'],
    ['python3', 'aglo_learned_nodes.py', '-int', '[2,21]', '-st', '/Users/antoniomendez/Library/CloudStorage/GoogleDrive-angel.mendez@cimat.mx/Mi unidad/Tesis/Datos/Adj_eco/matrices_estaciones/est_2024.npy', '-cell', 'station_cells/station_cells_ecobici_2024_6.pkl', '-nodes', 'station_cells/nodes_eco_6.npy', '-index', '275', '-sys', 'ecobici', '-part', '6', '-input', '/Users/antoniomendez/Library/CloudStorage/GoogleDrive-angel.mendez@cimat.mx/Mi unidad/angel_inference_dictionary_learning/eco/results_2024_22n_12a_noreg', '-out', f'nodes_clustering_results/day_0210_eco_22n_12a_noreg'],
    ['python3', 'aglo_learned_nodes.py', '-int', '[2,21]', '-st', '/Users/antoniomendez/Library/CloudStorage/GoogleDrive-angel.mendez@cimat.mx/Mi unidad/Tesis/Datos/Adj_mibici/matrices_estaciones/est_2024.npy', '-cell', 'station_cells/station_cells_mibici_2024_10.pkl', '-nodes', 'station_cells/nodes_mibici_10.npy', '-index', '275', '-sys', 'mibici', '-part', '10', '-input', '/Users/antoniomendez/Library/CloudStorage/GoogleDrive-angel.mendez@cimat.mx/Mi unidad/angel_inference_dictionary_learning/mibici/results_2024_22n_12a_reg', '-out', f'nodes_clustering_results/day_0210_mibici_22n_12a_reg'],
    ['python3', 'aglo_learned_nodes.py', '-int', '[2,21]', '-st', '/Users/antoniomendez/Library/CloudStorage/GoogleDrive-angel.mendez@cimat.mx/Mi unidad/Tesis/Datos/Adj_mibici/matrices_estaciones/est_2024.npy', '-cell', 'station_cells/station_cells_mibici_2024_10.pkl', '-nodes', 'station_cells/nodes_mibici_10.npy', '-index', '275', '-sys', 'mibici', '-part', '10', '-input', '/Users/antoniomendez/Library/CloudStorage/GoogleDrive-angel.mendez@cimat.mx/Mi unidad/angel_inference_dictionary_learning/mibici/results_2024_22n_12a_noreg', '-out', f'nodes_clustering_results/day_0210_mibici_22n_12a_noreg'],
    ['python3', 'aglo_learned_nodes.py', '-int', '[2,21]', '-st', '/Users/antoniomendez/Library/CloudStorage/GoogleDrive-angel.mendez@cimat.mx/Mi unidad/Tesis/Datos/Adj_eco/matrices_estaciones/est_2020.npy', '-cell', 'station_cells/station_cells_ecobici_2020_4.pkl', '-nodes', 'station_cells/nodes_eco_4.npy', '-index', '77', '-sys', 'ecobici', '-part', '4', '-input', '/Users/antoniomendez/Library/CloudStorage/GoogleDrive-angel.mendez@cimat.mx/Mi unidad/angel_inference_dictionary_learning/eco/results_2020_22n_12a_reg', '-out', f'nodes_clustering_results/day_180320_eco_22n_12a_reg'],
    ['python3', 'aglo_learned_nodes.py', '-int', '[2,21]', '-st', '/Users/antoniomendez/Library/CloudStorage/GoogleDrive-angel.mendez@cimat.mx/Mi unidad/Tesis/Datos/Adj_eco/matrices_estaciones/est_2020.npy', '-cell', 'station_cells/station_cells_ecobici_2020_4.pkl', '-nodes', 'station_cells/nodes_eco_4.npy', '-index', '77', '-sys', 'ecobici', '-part', '4', '-input', '/Users/antoniomendez/Library/CloudStorage/GoogleDrive-angel.mendez@cimat.mx/Mi unidad/angel_inference_dictionary_learning/eco/results_2020_22n_12a_noreg', '-out', f'nodes_clustering_results/day_180320_eco_22n_12a_noreg'],
    ['python3', 'aglo_learned_nodes.py', '-int', '[2,21]', '-st', '/Users/antoniomendez/Library/CloudStorage/GoogleDrive-angel.mendez@cimat.mx/Mi unidad/Tesis/Datos/Adj_mibici/matrices_estaciones/est_2020.npy', '-cell', 'station_cells/station_cells_mibici_2020_6.pkl', '-nodes', 'station_cells/nodes_mibici_6.npy', '-index', '77', '-sys', 'mibici', '-part', '6', '-input', '/Users/antoniomendez/Library/CloudStorage/GoogleDrive-angel.mendez@cimat.mx/Mi unidad/angel_inference_dictionary_learning/mibici/results_2020_22n_12a_reg', '-out', f'nodes_clustering_results/day_180320_mibici_22n_12a_reg'],
    ['python3', 'aglo_learned_nodes.py', '-int', '[2,21]', '-st', '/Users/antoniomendez/Library/CloudStorage/GoogleDrive-angel.mendez@cimat.mx/Mi unidad/Tesis/Datos/Adj_mibici/matrices_estaciones/est_2020.npy', '-cell', 'station_cells/station_cells_mibici_2020_6.pkl', '-nodes', 'station_cells/nodes_mibici_6.npy', '-index', '77', '-sys', 'mibici', '-part', '6', '-input', '/Users/antoniomendez/Library/CloudStorage/GoogleDrive-angel.mendez@cimat.mx/Mi unidad/angel_inference_dictionary_learning/mibici/results_2024_22n_12a_noreg', '-out', f'nodes_clustering_results/day_180320_mibici_22n_12a_noreg'],
    ['python3', 'aglo_learned_nodes.py', '-int', '[2,45]', '-st', '/Users/antoniomendez/Library/CloudStorage/GoogleDrive-angel.mendez@cimat.mx/Mi unidad/Tesis/Datos/Adj_eco/matrices_estaciones/est_2020.npy', '-cell', 'station_cells/station_cells_ecobici_2020_6.pkl', '-nodes', 'station_cells/nodes_eco_6.npy', '-index', '77', '-sys', 'ecobici', '-part', '6', '-input', '/Users/antoniomendez/Library/CloudStorage/GoogleDrive-angel.mendez@cimat.mx/Mi unidad/angel_inference_dictionary_learning/eco/results_2020_46n_23a_reg', '-out', f'nodes_clustering_results/day_180320_eco_46n_23a_reg'],
    ['python3', 'aglo_learned_nodes.py', '-int', '[2,45]', '-st', '/Users/antoniomendez/Library/CloudStorage/GoogleDrive-angel.mendez@cimat.mx/Mi unidad/Tesis/Datos/Adj_eco/matrices_estaciones/est_2020.npy', '-cell', 'station_cells/station_cells_ecobici_2020_6.pkl', '-nodes', 'station_cells/nodes_eco_6.npy', '-index', '77', '-sys', 'ecobici', '-part', '6', '-input', '/Users/antoniomendez/Library/CloudStorage/GoogleDrive-angel.mendez@cimat.mx/Mi unidad/angel_inference_dictionary_learning/eco/results_2020_46n_23a_noreg', '-out', f'nodes_clustering_results/day_180320_eco_46n_23a_noreg'],
    ['python3', 'aglo_learned_nodes.py', '-int', '[2,44]', '-st', '/Users/antoniomendez/Library/CloudStorage/GoogleDrive-angel.mendez@cimat.mx/Mi unidad/Tesis/Datos/Adj_mibici/matrices_estaciones/est_2020.npy', '-cell', 'station_cells/station_cells_mibici_2020_10.pkl', '-nodes', 'station_cells/nodes_mibici_10.npy', '-index', '77', '-sys', 'mibici', '-part', '10', '-input', '/Users/antoniomendez/Library/CloudStorage/GoogleDrive-angel.mendez@cimat.mx/Mi unidad/angel_inference_dictionary_learning/mibici/results_2020_45n_22a_reg', '-out', f'nodes_clustering_results/day_180320_mibici_45n_22a_reg'],
    ['python3', 'aglo_learned_nodes.py', '-int', '[2,44]', '-st', '/Users/antoniomendez/Library/CloudStorage/GoogleDrive-angel.mendez@cimat.mx/Mi unidad/Tesis/Datos/Adj_mibici/matrices_estaciones/est_2020.npy', '-cell', 'station_cells/station_cells_mibici_2020_10.pkl', '-nodes', 'station_cells/nodes_mibici_10.npy', '-index', '77', '-sys', 'mibici', '-part', '10', '-input', '/Users/antoniomendez/Library/CloudStorage/GoogleDrive-angel.mendez@cimat.mx/Mi unidad/angel_inference_dictionary_learning/mibici/results_2024_45n_22a_noreg', '-out', f'nodes_clustering_results/day_180320_mibici_45n_22a_noreg'],
    ['python3', 'aglo_learned_nodes.py', '-int', '[2,21]', '-st', '/Users/antoniomendez/Library/CloudStorage/GoogleDrive-angel.mendez@cimat.mx/Mi unidad/Tesis/Datos/Adj_eco/matrices_estaciones/est_2020.npy', '-cell', 'station_cells/station_cells_ecobici_2020_4.pkl', '-nodes', 'station_cells/nodes_eco_4.npy', '-index', '91', '-sys', 'ecobici', '-part', '4', '-input', '/Users/antoniomendez/Library/CloudStorage/GoogleDrive-angel.mendez@cimat.mx/Mi unidad/angel_inference_dictionary_learning/eco/results_2020_22n_12a_reg', '-out', f'nodes_clustering_results/day_010420_eco_22n_12a_reg'],
    ['python3', 'aglo_learned_nodes.py', '-int', '[2,21]', '-st', '/Users/antoniomendez/Library/CloudStorage/GoogleDrive-angel.mendez@cimat.mx/Mi unidad/Tesis/Datos/Adj_eco/matrices_estaciones/est_2020.npy', '-cell', 'station_cells/station_cells_ecobici_2020_4.pkl', '-nodes', 'station_cells/nodes_eco_4.npy', '-index', '91', '-sys', 'ecobici', '-part', '4', '-input', '/Users/antoniomendez/Library/CloudStorage/GoogleDrive-angel.mendez@cimat.mx/Mi unidad/angel_inference_dictionary_learning/eco/results_2020_22n_12a_noreg', '-out', f'nodes_clustering_results/day_010420_eco_22n_12a_noreg'],
    ['python3', 'aglo_learned_nodes.py', '-int', '[2,21]', '-st', '/Users/antoniomendez/Library/CloudStorage/GoogleDrive-angel.mendez@cimat.mx/Mi unidad/Tesis/Datos/Adj_mibici/matrices_estaciones/est_2020.npy', '-cell', 'station_cells/station_cells_mibici_2020_6.pkl', '-nodes', 'station_cells/nodes_mibici_6.npy', '-index', '91', '-sys', 'mibici', '-part', '6', '-input', '/Users/antoniomendez/Library/CloudStorage/GoogleDrive-angel.mendez@cimat.mx/Mi unidad/angel_inference_dictionary_learning/mibici/results_2020_22n_12a_reg', '-out', f'nodes_clustering_results/day_010420_mibici_22n_12a_reg'],
    ['python3', 'aglo_learned_nodes.py', '-int', '[2,21]', '-st', '/Users/antoniomendez/Library/CloudStorage/GoogleDrive-angel.mendez@cimat.mx/Mi unidad/Tesis/Datos/Adj_mibici/matrices_estaciones/est_2020.npy', '-cell', 'station_cells/station_cells_mibici_2020_6.pkl', '-nodes', 'station_cells/nodes_mibici_6.npy', '-index', '91', '-sys', 'mibici', '-part', '6', '-input', '/Users/antoniomendez/Library/CloudStorage/GoogleDrive-angel.mendez@cimat.mx/Mi unidad/angel_inference_dictionary_learning/mibici/results_2024_22n_12a_noreg', '-out', f'nodes_clustering_results/day_010420_mibici_22n_12a_noreg'],
    ['python3', 'aglo_learned_nodes.py', '-int', '[2,45]', '-st', '/Users/antoniomendez/Library/CloudStorage/GoogleDrive-angel.mendez@cimat.mx/Mi unidad/Tesis/Datos/Adj_eco/matrices_estaciones/est_2020.npy', '-cell', 'station_cells/station_cells_ecobici_2020_6.pkl', '-nodes', 'station_cells/nodes_eco_6.npy', '-index', '91', '-sys', 'ecobici', '-part', '6', '-input', '/Users/antoniomendez/Library/CloudStorage/GoogleDrive-angel.mendez@cimat.mx/Mi unidad/angel_inference_dictionary_learning/eco/results_2020_46n_23a_reg', '-out', f'nodes_clustering_results/day_010420_eco_46n_23a_reg'],
    ['python3', 'aglo_learned_nodes.py', '-int', '[2,45]', '-st', '/Users/antoniomendez/Library/CloudStorage/GoogleDrive-angel.mendez@cimat.mx/Mi unidad/Tesis/Datos/Adj_eco/matrices_estaciones/est_2020.npy', '-cell', 'station_cells/station_cells_ecobici_2020_6.pkl', '-nodes', 'station_cells/nodes_eco_6.npy', '-index', '91', '-sys', 'ecobici', '-part', '6', '-input', '/Users/antoniomendez/Library/CloudStorage/GoogleDrive-angel.mendez@cimat.mx/Mi unidad/angel_inference_dictionary_learning/eco/results_2020_46n_23a_noreg', '-out', f'nodes_clustering_results/day_010420_eco_46n_23a_noreg'],
    ['python3', 'aglo_learned_nodes.py', '-int', '[2,44]', '-st', '/Users/antoniomendez/Library/CloudStorage/GoogleDrive-angel.mendez@cimat.mx/Mi unidad/Tesis/Datos/Adj_mibici/matrices_estaciones/est_2020.npy', '-cell', 'station_cells/station_cells_mibici_2020_10.pkl', '-nodes', 'station_cells/nodes_mibici_10.npy', '-index', '91', '-sys', 'mibici', '-part', '10', '-input', '/Users/antoniomendez/Library/CloudStorage/GoogleDrive-angel.mendez@cimat.mx/Mi unidad/angel_inference_dictionary_learning/mibici/results_2020_45n_22a_reg', '-out', f'nodes_clustering_results/day_010420_mibici_45n_22a_reg'],
    ['python3', 'aglo_learned_nodes.py', '-int', '[2,44]', '-st', '/Users/antoniomendez/Library/CloudStorage/GoogleDrive-angel.mendez@cimat.mx/Mi unidad/Tesis/Datos/Adj_mibici/matrices_estaciones/est_2020.npy', '-cell', 'station_cells/station_cells_mibici_2020_10.pkl', '-nodes', 'station_cells/nodes_mibici_10.npy', '-index', '91', '-sys', 'mibici', '-part', '10', '-input', '/Users/antoniomendez/Library/CloudStorage/GoogleDrive-angel.mendez@cimat.mx/Mi unidad/angel_inference_dictionary_learning/mibici/results_2024_45n_22a_noreg', '-out', f'nodes_clustering_results/day_010420_mibici_45n_22a_noreg']
]

for i, cmd in enumerate(experiments):
    print(f'Running command {i+1} of {len(experiments)}')
    subprocess.run(cmd)

os.system(f'curl -d "Projects Finished!!!" ntfy.sh/aamh_091099_ntfy')